# Generated by Django 4.1.3 on 2022-11-14 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('amount', models.FloatField()),
                ('transfer_type', models.CharField(max_length=16)),
                ('balance', models.FloatField()),
                ('remark', models.CharField(max_length=1024)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_transactions', to='authentication.users')),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('status', models.SmallIntegerField(default=0)),
                ('requested_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_money_requests', to='authentication.users')),
            ],
            options={
                'db_table': 'requests',
            },
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('balance', models.FloatField(default=0.0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.users')),
            ],
            options={
                'db_table': 'balances',
            },
        ),
    ]
