# Generated by Django 4.1.3 on 2022-11-14 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('wallet', '0002_alter_transactions_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requests',
            old_name='requested_user',
            new_name='requested_by',
        ),
        migrations.AddField(
            model_name='requests',
            name='requested_to',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_requests', to='authentication.users'),
        ),
    ]
